#!/bin/sh
#
# collectd

# Source function library.
. /etc/rc.d/init.d/functions

RETVAL=0
CONF=/etc/collectd.conf
prog="collectd"
PATH=$PATH:/usr/local/bin

lock=/var/lock/subsys/$prog

start() {
	# Start daemons.
	echo -n $"Starting $prog: "
	sync_collectd_rrd.sh -i
	daemon /usr/sbin/$prog -C $CONF 2>/dev/null
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && touch $lock
	return $RETVAL
}

stop() {

	# Stop daemons.
	echo -n $"Shutting down $prog: "
	killproc $prog
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && rm -f $lock
	[ $RETVAL -eq 0 ] && sync_collectd_rrd.sh
	return $RETVAL
}

restart() {
        stop
        start
}


# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	RETVAL=$?
	;;
  condrestart)
        status $prog &>/dev/null && restart || :
	;;
  condstop)
        status $prog &>/dev/null && stop || :
	;;
  status)
	status $prog
	RETVAL=$?
	;;
  *)
	echo $"Usage: $0 {start|stop|restart|condrestart|condstop|status}"
	exit 1
esac

exit $RETVAL

