package SimpleCurses;

use strict;
use warnings;

sub new {
    my ($class, %args) = @_;
    my $self = {
        width  => $args{width} || 80,
        height => $args{height} || 24,
    };
    return bless $self, $class;
}

sub init_screen {
    system("clear");
    print "\e[?25l"; # Hide cursor
}

sub end_screen {
    print "\e[?25h"; # Show cursor
#    system("clear");
}

sub draw_box {
    my ($self, $x, $y, $width, $height) = @_;
    my $horizontal = '─';
    my $vertical   = '│';
    my $corner_tl  = '┌';
    my $corner_tr  = '┐';
    my $corner_bl  = '└';
    my $corner_br  = '┘';

    # Top border
    print "\e[${y};${x}H$corner_tl" . ($horizontal x ($width - 2)) . "$corner_tr";
    
    # Side borders
    for my $line (1 .. $height - 2) {
        print "\e[" . ($y + $line) . ";${x}H$vertical";
        print "\e[" . ($y + $line) . ";" . ($x + $width - 1) . "H$vertical";
    }

    # Bottom border
    print "\e[" . ($y + $height - 1) . ";${x}H$corner_bl" . ($horizontal x ($width - 2)) . "$corner_br";
}

sub write_text {
    my ($self, $x, $y, $text) = @_;
    print "\e[${y};${x}H$text";
}

sub get_input {
    system("stty raw -echo");
    my $key = getc(STDIN);
    system("stty -raw echo");
    return $key;
}

1;

__END__

=head1 NAME

SimpleCurses - A simple module for creating graphical windows in the Linux CLI.

=head1 SYNOPSIS

    use SimpleCurses;

    my $screen = SimpleCurses->new();
    $screen->init_screen();

    $screen->draw_box(10, 5, 40, 10);
    $screen->write_text(12, 7, 'Hello, world!');

    my $key = $screen->get_input();
    $screen->end_screen();

=head1 DESCRIPTION

This module provides basic graphical windowing functionality using ANSI escape codes.

=head1 METHODS

=over 4

=item new(%args)

Creates a new SimpleCurses object. Accepts optional arguments for width and height.

=item init_screen()

Initializes the screen for graphical output.

=item end_screen()

Restores the terminal to normal mode.

=item draw_box($x, $y, $width, $height)

Draws a box at the specified coordinates with the given width and height.

=item write_text($x, $y, $text)

Writes text at the specified coordinates.

=item get_input()

Waits for and returns a single key press from the user.

=back

=head1 AUTHOR

Generated by ChatGPT.

=cut

