#!/bin/sh

. /etc/rc.d/efw_lib.sh
. ${UPLINK_SCRIPTS}/generic/detect.sh

detect_usb 0959 2bd0
detect_usb 0675 1688
detect_usb 07b0 0007
detect_usb 0742 2008
detect_usb 0742 2009
detect_usb 0742 200A
detect_usb 08e3 0301
detect_usb 07fa 0846
detect_usb 07fa 0847
detect_usb 07b0 0006
detect_show
