#!/bin/sh
#
# chkconfig: 345 81 19
# description: ulogd is the userspace logging daemon for netfilter/iptables
#


. /etc/rc.d/init.d/functions

ULOGD_PID=/var/run/ulogd.pid

function start()
{
	printf "Starting ulogd"
    if [ -f $ULOGD_PID ]; then
        ps -p $(cat $ULOGD_PID) &>/dev/null || rm -f $ULOGD_PID
    fi
	daemon /usr/sbin/ulogd -d -p $ULOGD_PID
	echo
	touch /var/lock/subsys/ulogd
}


function stop()
{
	printf "Stopping ulogd"
	killproc ulogd
    RETVAL=$?
    echo
    if [ $RETVAL -eq 0 ]; then
        test -f $ULOGD_PID && rm -f $ULOGD_PID
    fi
	echo
	rm -f /var/lock/subsys/ulogd
}


function reload()
{
	pid=`pidof ulogd`
	if [ "x$pid" != "x" ]; then
		kill -HUP $pid 2>/dev/null
	fi
	touch /var/lock/subsys/ulogd
}


case "$1" in
  start)
	start
	;;
  stop)
  	stop
	;;
  restart)
	stop
	start
	;;
  reload)
	reload
	;;
  status)
	status ulogd
	;;
  *)
	printf "Usage: %s {start|stop|status|restart|reload}\n" "ulogd"
	exit 1
esac

exit 0
