
### Dependencies
DEP_BINS=perl iptables iptables-save iptables-restore mktemp cat grep bash
DEP_PMODS=File::Basename Config::Simple Getopt::Long

### Lists of files to be installed
F_CNF=firewall.conf interfaces.conf
F_HELPERS=icmp.conf icmpv6.conf samba.conf apple-ios.conf avg.conf dhcp.conf dhcpv6.conf mail.conf dns.conf snmp.conf sql.conf gotomeeting.conf pptp.conf nfs.conf


###############################################################################

all: install

install: test bin config
	# install the actual scripts
	install -D -m 0755 src/razwall.pl	/razwall/firewall/razwall.pl			#/usr/local/sbin/razwall
	install -D -m 0755 src/fwfire.sh	/razwall/firewall/fwfire.sh				#/usr/local/sbin/fwfire
	install -D -m 0755 src/fwlog2rule.pl	/razwall/firewall/fwlog2rule.pl		#/usr/local/sbin/fwlog2rule

	# ... hook directories
	install -d -m0755 /razwall/firewall/pre.d	#/etc/razwall/pre.d
	install -d -m0755 /razwall/firewall/post.d	#/etc/razwall/post.d
	# systemd unit
	install -Dm0644 razwall.service /etc/rc.d/rc.razwall	#/usr/local/lib/systemd/system/razwall.service


test:
	@echo "==> Checking for required external dependencies"
	for bindep in $(DEP_BINS) ; do \
		which $$bindep > /dev/null || { echo "$$bindep not found"; exit 1;} ; \
	done

	@echo "==> Checking for required perl modules"
	for pmod in $(DEP_PMODS) ; do \
		perl -M$$pmod -e 1 || { \
			echo '===> Missing Perl Modules detected; Perhaps you need:' ; \
			echo 'RedHat: yum install perl-Config-Simple' ; \
			echo 'Debian: apt-get install libconfig-simple-perl' ; \
			exit 1; \
			} ; \
	done

	@echo "==> Checking for valid script syntax"
	@perl -c src/razwall.pl
	@perl -c src/fwlog2rule.pl
	@bash -n src/fwfire.sh

	@echo "==> All looks good!"

bin: test src/razwall.pl src/fwfire.sh src/fwlog2rule.pl

config: $(F_CNF)
	# Install Distribution Helper Rule Files
	for f in $(F_HELPERS) ; do \
		install -D -m 0444 helpers/$$f /etc/razwall/helpers/$$f || exit 1 ; \
	done
	# Install (without overwriting) configuration files
	for f in $(F_CNF) ; do \
		[ -e /etc/razwall/$$f ] || \
			install -D -m 0644 $$f /etc/razwall/$$f ; \
	done
