#!/bin/sh


. /etc/rc.d/efw_lib.sh
. ${UPLINK_SCRIPTS}/common
. ${UPLINK_SCRIPTS}/generic/dhcp.sh

function start() {
    dhcp_kill $interface
    dhcp_start || failure
    return 0
}

function stop() {
    dhcp_stop
    return $?
}

switch "$1"

exit 0
